name: Auto distribuild feeds

on:
  workflow_run:
    workflows: ["Auto compile with openwrt sdk"]
    types:
      - completed

permissions:
  contents: write

jobs:
  distribuild:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v4

      - name: Get latest release tag
        id: get_release
        run: |
          tag=$(gh release list --limit 1 --json tagName --jq '.[0].tagName')
          echo "tag=$tag" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download release assets
        run: |
          mkdir release_assets
          gh release download ${{ steps.get_release.outputs.tag }} --dir release_assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare feed directories
        env:
          FEED_VERSION: ${{ steps.get_release.outputs.tag }}
        run: |
          mkdir -p public/${FEED_VERSION}

          # 自动检测 release_assets/upload 下有哪些架构目录
          for arch in $(ls release_assets/upload); do
            mkdir -p public/${FEED_VERSION}/${arch}

            # luci 包（架构无关，复制到每个架构目录）
            cp -r release_assets/mypackage/*.ipk public/${FEED_VERSION}/${arch}/ || true

            # 架构相关包
            cp -r release_assets/upload/${arch}/packages/*.ipk public/${FEED_VERSION}/${arch}/ || true

            # 生成 Packages 索引
            ./staging_dir/host/bin/opkg-make-index public/${FEED_VERSION}/${arch} > public/${FEED_VERSION}/${arch}/Packages
            gzip -9nc public/${FEED_VERSION}/${arch}/Packages > public/${FEED_VERSION}/${arch}/Packages.gz

            # 生成架构目录 index.html
            {
              echo "<html><head><meta charset='utf-8'><title>Feed for ${arch}</title></head><body>"
              echo "<h1>Packages for ${arch}</h1><ul>"
              for f in $(ls public/${FEED_VERSION}/${arch}); do
                echo "<li><a href=\"$f\">$f</a></li>"
              done
              echo "</ul></body></html>"
            } > public/${FEED_VERSION}/${arch}/index.html
          done

          # 顶层 index.html
          {
            echo "<html><head><meta charset='utf-8'><title>Feed ${FEED_VERSION}</title></head><body>"
            echo "<h1>Feed version ${FEED_VERSION}</h1><ul>"
            for arch in $(ls public/${FEED_VERSION}); do
              echo "<li><a href=\"$arch/\">$arch</a></li>"
            done
            echo "</ul></body></html>"
          } > public/${FEED_VERSION}/index.html

          # 生成 latest.txt 文件
          echo "${FEED_VERSION}" > public/latest.txt

      - name: Deploy feed to GitHub Pages
        run: |
          cd public
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update feed $(date +'%Y-%m-%d %H:%M:%S')"
          git branch -M gh-pages
          git remote add origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git push -f origin gh-pages
