name: Debug Release Assets
permissions:
  contents: read

on:
  workflow_dispatch:   # 手动触发

jobs:
  debug-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check gh version
        run: gh --version
        env:
          GH_TOKEN: ${{ secrets.DL_RELEASE_ASSET }}

      - name: List releases (luci-theme-argon)
        run: gh release list --repo Jackie264/luci-theme-argon
        env:
          GH_TOKEN: ${{ secrets.DL_RELEASE_ASSET }}

      - name: Get latest tag (luci-theme-argon)
        id: argon_tag
        run: |
          tag=$(gh release list --repo Jackie264/luci-theme-argon --limit 1 --json tagName --jq '.[0].tagName')
          echo "tag=$tag"
          echo "tag=$tag" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.DL_RELEASE_ASSET }}

      - name: View release by tag (luci-theme-argon)
        run: gh release view ${{ steps.argon_tag.outputs.tag }} --repo Jackie264/luci-theme-argon --json tagName,isDraft,isPrerelease,assets
        env:
          GH_TOKEN: ${{ secrets.DL_RELEASE_ASSET }}
    
      - name: List releases (luci-app-advanced-reboot)
        run: gh release list --repo Jackie264/luci-app-advanced-reboot
        env:
          GH_TOKEN: ${{ secrets.DL_RELEASE_ASSET }}

      - name: Get latest tag (luci-app-advanced-reboot)
        id: reboot_tag
        run: |
          tag=$(gh release list --repo Jackie264/luci-app-advanced-reboot --limit 1 --json tagName --jq '.[0].tagName')
          echo "tag=$tag"
          echo "tag=$tag" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.DL_RELEASE_ASSET }}

      - name: View release by tag (luci-app-advanced-reboot)
        run: gh release view ${{ steps.reboot_tag.outputs.tag }} --repo Jackie264/luci-app-advanced-reboot --json tagName,isDraft,isPrerelease,assets
        env:
          GH_TOKEN: ${{ secrets.DL_RELEASE_ASSET }}

      - name: List releases (openwrt-passwall2)
        run: gh release list --repo Jackie264/openwrt-passwall2
        env:
          GH_TOKEN: ${{ secrets.DL_RELEASE_ASSET }}

      - name: Get latest tag (openwrt-passwall2)
        id: passwall2_tag
        run: |
          tag=$(gh release list --repo Jackie264/openwrt-passwall2 --limit 1 --json tagName --jq '.[0].tagName')
          echo "tag=$tag"
          echo "tag=$tag" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.DL_RELEASE_ASSET }}

      - name: View release by tag (openwrt-passwall2)
        run: gh release view ${{ steps.passwall2_tag.outputs.tag }} --repo Jackie264/openwrt-passwall2 --json tagName,isDraft,isPrerelease,assets
        env:
          GH_TOKEN: ${{ secrets.DL_RELEASE_ASSET }}
