name: Generate usign keypair with custom comment

on:
  workflow_dispatch:

jobs:
  gen-key:
    runs-on: ubuntu-latest
    steps:
    - name: Install build deps
      run: sudo apt-get update && sudo apt-get install -y build-essential libssl-dev

    - name: Build usign
      run: |
        git clone https://git.openwrt.org/project/usign.git
        cd usign && make && cd ..
        ./usign/usign -G -s usign.sec -p usign.pub
        # 替换第一行注释
        sed -i '1s/.*/untrusted comment: OpenWrt usign key of Jackie264/' usign.pub
        sed -i '1s/.*/untrusted comment: OpenWrt usign key of Jackie264/' usign.sec
        echo "===== PUBLIC KEY ====="
        cat usign.pub
        echo "===== PRIVATE KEY ====="
        cat usign.sec
