name: Generate usign keypair

on:
  workflow_dispatch:

jobs:
  gen-key:
    runs-on: ubuntu-latest
    steps:
    - name: Download OpenWrt SDK (x86_64 示例)
      run: |
        curl -fL -o sdk.tar.zst https://downloads.openwrt.org/releases/24.10.0/targets/x86/64/openwrt-sdk-24.10.0-x86-64_gcc-13.3.0_musl.Linux-x86_64.tar.zst
        mkdir openwrt
        tar --zstd -xf sdk.tar.zst -C openwrt --strip-components=1

    - name: Generate usign keypair
      run: |
        cd openwrt
        staging_dir/host/bin/usign -G -s usign.sec -p usign.pub
        echo "===== PUBLIC KEY ====="
        cat usign.pub
        echo "===== PRIVATE KEY ====="
        cat usign.sec
